id: EDL Performance Test - Timeout
version: -1
fromversion: 5.5.0
name: EDL Performance Test - Timeout
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3def372d-3c46-4c16-8f0a-47dde61d512f
    type: start
    task:
      id: 3def372d-3c46-4c16-8f0a-47dde61d512f
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 631e960a-565b-4556-8e72-10cadd53f0ab
    type: title
    task:
      id: 631e960a-565b-4556-8e72-10cadd53f0ab
      version: -1
      name: Timeout 3
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1155
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: e7a2921c-9b09-4154-8e46-6799db48da82
    type: playbook
    task:
      id: e7a2921c-9b09-4154-8e46-6799db48da82
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      c:
        simple: ${inputs.c}
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "3"
      url:
        simple: ${inputs.url}
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 4eff28d1-a3a5-4afe-8206-e6672ae65c2f
    type: title
    task:
      id: 4eff28d1-a3a5-4afe-8206-e6672ae65c2f
      version: -1
      name: Timeout 5
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 835
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 7e200bc7-59d5-4070-8687-03a81a5216df
    type: playbook
    task:
      id: 7e200bc7-59d5-4070-8687-03a81a5216df
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      c:
        simple: ${inputs.c}
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "5"
      url:
        simple: ${inputs.url}
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 980
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 51c2ce4f-7f41-40f0-8c64-9f146d3264e8
    type: title
    task:
      id: 51c2ce4f-7f41-40f0-8c64-9f146d3264e8
      version: -1
      name: Timeout 10
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: c6841008-f8b0-4645-8add-47cbe3ae5bf5
    type: playbook
    task:
      id: c6841008-f8b0-4645-8add-47cbe3ae5bf5
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      c:
        simple: ${inputs.c}
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "10"
      url:
        simple: ${inputs.url}
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: ec048309-a6fa-4795-84ad-6f4cae74a10e
    type: title
    task:
      id: ec048309-a6fa-4795-84ad-6f4cae74a10e
      version: -1
      name: Timeout 30
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: c44d2918-823e-448d-866b-c77e6b3a9ef4
    type: playbook
    task:
      id: c44d2918-823e-448d-866b-c77e6b3a9ef4
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      c:
        simple: ${inputs.c}
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "30"
      url:
        simple: ${inputs.url}
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1345,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: url
  value: {}
  required: false
  description: The URL of the EDL instance with with query in the end
  playbookInputQuery: null
- key: "n"
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: z
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: results_map
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: c
  value: {}
  required: false
  description: Concurrent requests to be sent.
  playbookInputQuery: null
outputs:
- contextPath: Hey
  type: unknown
sourceplaybookid: 37d1cfda-2d21-4eab-87fa-4449cf2f5427
