id: EDL Performance Test - Concurrency
version: -1
fromversion: 5.5.0
name: EDL Performance Test - Concurrency
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e53331de-eb4b-48ee-8667-cebb6b9df20c
    type: start
    task:
      id: e53331de-eb4b-48ee-8667-cebb6b9df20c
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 2a200b95-b4f0-401d-80cb-07c4ba750feb
    type: title
    task:
      id: 2a200b95-b4f0-401d-80cb-07c4ba750feb
      version: -1
      name: Concurrency 1
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 6939d949-d80b-40ef-8eda-ec1cfc12fd8c
    type: playbook
    task:
      id: 6939d949-d80b-40ef-8eda-ec1cfc12fd8c
      version: -1
      name: EDL Performance Test - Timeout
      playbookName: EDL Performance Test - Timeout
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      c:
        simple: "1"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: a84fa40c-8ee7-4c26-827f-8e3a13d4592c
    type: title
    task:
      id: a84fa40c-8ee7-4c26-827f-8e3a13d4592c
      version: -1
      name: Concurrency 4
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 35751b0b-136e-4148-86e6-c909580d93ea
    type: playbook
    task:
      id: 35751b0b-136e-4148-86e6-c909580d93ea
      version: -1
      name: EDL Performance Test - Timeout
      playbookName: EDL Performance Test - Timeout
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      c:
        simple: "4"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: c2d3f0eb-bbbc-4c35-8947-88f087c133a8
    type: title
    task:
      id: c2d3f0eb-bbbc-4c35-8947-88f087c133a8
      version: -1
      name: Concurrency 8
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 835
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: cb5d0bc5-6bea-409a-8595-dcc23d4cb27d
    type: playbook
    task:
      id: cb5d0bc5-6bea-409a-8595-dcc23d4cb27d
      version: -1
      name: EDL Performance Test - Timeout
      playbookName: EDL Performance Test - Timeout
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      c:
        simple: "8"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 980
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 28e92586-713d-4edd-8c1f-42eaf7d51872
    type: title
    task:
      id: 28e92586-713d-4edd-8c1f-42eaf7d51872
      version: -1
      name: Concurrency 16
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1155
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: de5f1b47-4c33-4419-804b-15b6f540617d
    type: playbook
    task:
      id: de5f1b47-4c33-4419-804b-15b6f540617d
      version: -1
      name: EDL Performance Test - Timeout
      playbookName: EDL Performance Test - Timeout
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      c:
        simple: "16"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1345,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: url
  value: {}
  required: false
  description: The URL of the EDL instance with with query in the end
  playbookInputQuery: null
- key: results_map
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: "n"
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: z
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
outputs:
- contextPath: Hey
  type: unknown
sourceplaybookid: 37d1cfda-2d21-4eab-87fa-4449cf2f5427
