id: EDL Performance Test - Concurrency
version: -1
fromversion: 5.5.0
name: EDL Performance Test - Concurrency
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 58ddedec-ec9b-400a-8475-44f960138f83
    type: start
    task:
      id: 58ddedec-ec9b-400a-8475-44f960138f83
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 1726f02e-2802-4379-83e3-3719c9f415b6
    type: title
    task:
      id: 1726f02e-2802-4379-83e3-3719c9f415b6
      version: -1
      name: Concurrency 1
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 52fcbd14-a3a3-43ac-8e79-c8706525be37
    type: title
    task:
      id: 52fcbd14-a3a3-43ac-8e79-c8706525be37
      version: -1
      name: Concurrency 10
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: e75c46c9-75fd-44c1-8f9b-0216124dcd1a
    type: title
    task:
      id: e75c46c9-75fd-44c1-8f9b-0216124dcd1a
      version: -1
      name: Concurrency 20
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 835
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 362d01cd-fde8-4015-84b7-8077039482af
    type: title
    task:
      id: 362d01cd-fde8-4015-84b7-8077039482af
      version: -1
      name: Concurrency 100
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1155
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: bda3dadd-e66a-4dee-8808-4d650a30d295
    type: title
    task:
      id: bda3dadd-e66a-4dee-8808-4d650a30d295
      version: -1
      name: Concurrency 200
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1475
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 2dbcb848-a52c-4476-8925-4a3586cdf3f7
    type: playbook
    task:
      id: 2dbcb848-a52c-4476-8925-4a3586cdf3f7
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      c:
        simple: "1"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "2"
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 2f278c79-b488-41bf-844d-9bd22a74f62f
    type: playbook
    task:
      id: 2f278c79-b488-41bf-844d-9bd22a74f62f
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      c:
        simple: "10"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "2"
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 387572ca-e958-40d8-8709-20582c07dd75
    type: playbook
    task:
      id: 387572ca-e958-40d8-8709-20582c07dd75
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      c:
        simple: "20"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "2"
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 980
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: ac38c0da-9689-4ffb-8860-d5bb6c70e85d
    type: playbook
    task:
      id: ac38c0da-9689-4ffb-8860-d5bb6c70e85d
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      c:
        simple: "100"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "2"
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: cfd9fdd9-6bf1-4a14-8d19-386563b1c0b5
    type: playbook
    task:
      id: cfd9fdd9-6bf1-4a14-8d19-386563b1c0b5
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      c:
        simple: "200"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "2"
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1620
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1665,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: url
  value: {}
  required: false
  description: The URL of the EDL instance with with query in the end
  playbookInputQuery: null
- key: results_map
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: "n"
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: z
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
outputs:
- contextPath: Hey
  type: unknown
sourceplaybookid: 37d1cfda-2d21-4eab-87fa-4449cf2f5427
tests:
- No test
