id: EDL Indicator Performance Test
version: -1
fromversion: 6.0.0
name: EDL Indicator Performance Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 483a1d4e-fdfc-42b2-86b1-9a79d45e797c
    type: start
    task:
      id: 483a1d4e-fdfc-42b2-86b1-9a79d45e797c
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 7f7c541d-d6a3-4874-8be2-5224c1c64f2d
    type: regular
    task:
      id: 7f7c541d-d6a3-4874-8be2-5224c1c64f2d
      version: -1
      name: Hey edl IP
      scriptName: Hey
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      c:
        simple: ${inputs.c}
      "n":
        simple: ${inputs.n}
      results_map:
        simple: Type=IP
      t:
        simple: ${inputs.t}
      url:
        complex:
          root: inputs.url
          transformers:
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: '&q=type:IP'
      z:
        simple: ${inputs.z}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 9a03c737-5a5c-46bd-8fb2-71f39606c5de
    type: regular
    task:
      id: 9a03c737-5a5c-46bd-8fb2-71f39606c5de
      version: -1
      name: Hey edl URL
      scriptName: Hey
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      c:
        simple: ${inputs.c}
      "n":
        simple: ${inputs.n}
      results_map:
        simple: Type=URL
      t:
        simple: ${inputs.t}
      url:
        complex:
          root: inputs.url
          transformers:
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: '&q=type:URL'
      z:
        simple: ${inputs.z}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: d497e20e-1f9d-4929-8c8a-b33591536f35
    type: regular
    task:
      id: d497e20e-1f9d-4929-8c8a-b33591536f35
      version: -1
      name: Hey edl Domain
      scriptName: Hey
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      c:
        simple: ${inputs.c}
      "n":
        simple: ${inputs.n}
      results_map:
        simple: Type=Domain
      t:
        simple: ${inputs.t}
      url:
        complex:
          root: inputs.url
          transformers:
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: '&q=type:Domain'
      z:
        simple: ${inputs.z}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 570
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: ce50328a-84a0-48ed-85fd-15bc1c0691d9
    type: condition
    task:
      id: ce50328a-84a0-48ed-85fd-15bc1c0691d9
      version: -1
      name: Assert All Requests Received Successful Responses
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              complex:
                root: Hey
                accessor: Requests
            iscontext: true
          right:
            value:
              complex:
                root: Hey
                accessor: SuccessfulResponses
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 2c40dcec-74d7-49a1-80b9-57ad0aba55fb
    type: title
    task:
      id: 2c40dcec-74d7-49a1-80b9-57ad0aba55fb
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 940
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 955,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: url
  value: {}
  required: false
  description: The URL of the EDL instance with with query in the end
  playbookInputQuery: null
- key: "n"
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: t
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: z
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: results_map
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: c
  value: {}
  required: false
  description: Concurrent requests to be sent.
  playbookInputQuery: null
outputs:
- contextPath: Hey
  type: unknown
tests:
- No test
